name: ModTRS
main: yetanotherx.bukkitplugin.ModTRS.ModTRS
version: 2.1
database: true
commands:
    modreq:
        description: Request help from a moderator
        usage: /<command> [message]
    check:
        description: List all the currently open requests. Use p:# to go to a page, and t:open/t:all to change the type of the request
        usage: /<command> [p:#] [t:open|all]
    check-id:
        description: Read a request
        usage: /<command> [id]
        aliases: [checkid]
    tp-id:
        description: Teleport to the location of a request
        usage: /<command> [id]
        aliases: [tpid]
    claim:
        description: Claim a request
        usage: /<command> [id]
    unclaim:
        description: Unclaim a request
        usage: /<command> [id]
    complete:
        description: Mark a request as complete
        usage: /<command> [id]
        aliases: [done]
    reopen:
        description: Reopen a request
        usage: /<command> [id]
    hold:
        description: Put request on hold
        usage: /<command> [id]
    modreq-ban:
        description: Ban a user from making mod requests
        usage: /<command> [username]
    modreq-unban:
        description: Reallow a user to make mod requests
        usage: /<command> [username]
    mod-broadcast:
        description: Send a message to other moderators
        usage: /<command> [message]
        aliases: [mb]
    modlist:
        description: List all currently online moderators
        usage: /<command>
    modtrs:
        description: Command line only
        usage: /<command>
permissions:
    modtrs:
        description: Grants all permissions for ModTRS.
        children:
            modtrs.command.ban: false 
            modtrs.command.check: false 
            modtrs.command.check.self: true
            modtrs.command.complete: false 
            modtrs.command.broadcast: false 
            modtrs.command.modlist: true
            modtrs.command.modreq: true
            modtrs.mod: false 
            modtrs.command.reload: false 
            modtrs.command.teleport: false 
            modtrs.command.unban: false 
            modtrs.command.version: true
    modtrs.command.ban:
        description: Permission to use /modreq-ban
    modtrs.command.check: 
        description: Permission to use /check to see all open requests
    modtrs.command.check.self:
        description: Permission to use /check to see your own requests
    modtrs.command.complete: 
        description: Permission to use /done, /claim, /unclaim, /hold
    modtrs.command.broadcast:
        description: Permission to use /mod-broadcast
    modtrs.command.modlist:
        description: Permission to use /modlist
    modtrs.command.modreq:
        description: Permission to use /modreq
    modtrs.mod:
        description: Give this to all moderators. This is used for /modlist and /mb
    modtrs.command.reload:
        description: Permission to use /modtrs reload
    modtrs.command.teleport:
        description: Permission to use /tp-id
    modtrs.command.unban:
        description: Permission to use /modreq-unban
    modtrs.command.version:
        description: Permission to use /modtrs version