name: ModTRS
main: yetanotherx.bukkitplugin.ModTRS.ModTRS
version: 1.4.1
commands:
    modreq:
        description: Request help from a moderator
        usage: /<command> [message]
        permission: modtrs.command.modreq
    check:
        description: List all the currently open requests. Use p:# to go to a page, and t:open/t:all to change the type of the request
        usage: /<command> [p:#] [t:open|all]
    check-id:
        description: Read a request
        usage: /<command> [id]
    tp-id:
        description: Teleport to the location of a request
        usage: /<command> [id]
    claim:
        description: Claim a request
        usage: /<command> [id]
    unclaim:
        description: Unclaim a request
        usage: /<command> [id]
    complete:
        description: Mark a request as complete
        usage: /<command> [id]
        aliases: [done]
    reopen:
        description: Reopen a request
        usage: /<command> [id]
    hold:
        description: Put request on hold
        usage: /<command> [id]
    mod-broadcast:
        description: Send a message to other moderators
        usage: /<command> [message]
        aliases: [mb]
    modlist:
        description: List all currently online moderators
        usage: /<command>
    modtrs:
        description: Command line only
        usage: /<command>
    modtrs-reload:
        description: Reload the configuration
        usage: /<command>